# Generated by Django 5.1.6 on 2025-02-22 16:17

import books.validators_files.fileValidators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=50)),
                ('book_description', models.CharField(blank=True, max_length=200, null=True)),
                ('book_author', models.CharField(blank=True, max_length=100, null=True)),
                ('book_page', models.IntegerField(blank=True, null=True)),
                ('book_publications', models.CharField(blank=True, max_length=200, null=True)),
                ('book_image', models.FileField(blank=True, null=True, upload_to='books/', validators=[books.validators_files.fileValidators.file_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
