# Generated by Django 5.1.6 on 2025-02-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="book_publications",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
