# Generated by Django 5.1.3 on 2025-02-12 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeModel',
            new_name='Employee',
        ),
    ]
