# Generated by Django 5.1.3 on 2025-02-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_employee_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_image',
            field=models.FileField(blank=True, null=True, upload_to='employee_profile_image/'),
        ),
    ]
