# Generated by Django 5.1.6 on 2025-02-20 04:39

import category.validators_files.fileValidators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=200)),
                (
                    "category_image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="category_image/",
                        validators=[category.validators_files.fileValidators.file_size],
                    ),
                ),
            ],
        ),
    ]
