# Generated by Django 5.1.3 on 2025-02-23 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Branch', '0002_branch_created_at_branch_deleted_at_and_more'),
        ('category', '0002_category_created_at_category_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'branch',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('supplier_name', models.CharField(max_length=200)),
                ('product_code', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('stock_alert', models.IntegerField()),
                ('added_date', models.DateTimeField()),
                ('purchase_date', models.DateTimeField()),
                ('exp_date', models.DateTimeField()),
                ('purchase_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('total_price_with_vat', models.FloatField()),
                ('GC_number', models.CharField(max_length=50)),
                ('product_details', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.CASCADE, to='Branch.branch')),
                ('product_category', models.ForeignKey(db_column='product_category', on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
