# Generated by Django 5.1.6 on 2025-02-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_category", models.IntegerField()),
                ("product_name", models.CharField(max_length=200)),
                ("supplier_name", models.CharField(max_length=200)),
                ("branch", models.IntegerField()),
                ("product_code", models.CharField(max_length=20)),
                ("quantity", models.IntegerField()),
                ("stock_alert", models.IntegerField()),
                ("added_date", models.DateTimeField()),
                ("purchase_date", models.DateTimeField()),
                ("exp_date", models.DateTimeField()),
                ("purchase_price", models.FloatField()),
                ("total_price", models.FloatField()),
                ("total_price_with_vat", models.FloatField()),
                ("GC_number", models.CharField(max_length=50)),
                ("product_details", models.CharField(max_length=500)),
            ],
        ),
    ]
